# Generated by Django 4.0 on 2022-02-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('organ', models.CharField(max_length=50)),
                ('organ_date_time', models.DateTimeField()),
                ('smoke', models.BooleanField()),
                ('alcohol', models.BooleanField()),
                ('drug', models.BooleanField()),
                ('avg_sleep', models.PositiveIntegerField()),
                ('daily_exercise', models.PositiveIntegerField()),
            ],
        ),
    ]
